authentication/urls.py
from django.urls import path
from .views import UserLogin, UserSignup, UserLogout

app_name = 'authentication'

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('registration/', UserSignup.as_view(), name='registration'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, include
from .views import (ProjectsListView, UserProjectListView, UserProjectDetailView, AddComment, DeleteComment,
                    CreateProject, UpdateProject, DeleteProject, CreateGroup, CreateTask, EditTask, DeleteTask,
                    EditGroup, DeleteGroup, GroupListView, SearchProjects)

app_name = 'mainapp'

urlpatterns = [
    path("select2/", include("django_select2.urls")),

    # PROJECT SECTION
    path('', ProjectsListView.as_view(), name='main'),
    path('<slug:slug>', UserProjectListView.as_view(), name='user_proj'),
    path('create-project/', CreateProject.as_view(), name='new_project'),
    path('update-project/<slug:slug>/', UpdateProject.as_view(), name='update_project'),
    path('delete-project/<slug:slug>/', DeleteProject.as_view(), name='delete_project'),
    path('project/<slug:slug>/', UserProjectDetailView.as_view(), name='proj_details'),
    path('search/', SearchProjects.as_view(), name='search_projects'),

    # COMMENT SECTION
    path('project/<slug:slug>/add-comment/', AddComment.as_view(), name='add_comment'),
    path('delete-comment/<int:pk>/', DeleteComment.as_view(), name='delete_comment'),

    # GROUP SECTION
    path('<slug:slug>/project-groups/', GroupListView.as_view(), name='groups_list'),
    path('create-group/', CreateGroup.as_view(), name='create_group'),
    path('edit-group/<int:pk>/', EditGroup.as_view(), name='edit_group'),
    path('delete-group/<int:pk>/', DeleteGroup.as_view(), name='delete_group'),

    # TASK SECTION
    path('project/<slug:slug>/create-task/', CreateTask.as_view(), name='create_task'),
    path('project/<slug:slug>/edit-task/<int:pk>/', EditTask.as_view(), name='edit_task'),
    path('project/<slug:slug>/delete-task/<int:pk>/', DeleteTask.as_view(), name='delete_task'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from unidecode import unidecode
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.contrib.auth.models import Group

STATUS = (
    ('Стартовал', 'Started'),
    ('В процессе', 'In process'),
    ('Завершен', 'Finished'),
)

PRIORITY = (
    ('Низкий', 'Low'),
    ('Средний', 'Medium'),
    ('Высокий', 'High'),
    ('Наивысший', 'Highest'),
)


class Tag(models.Model):
    tag = models.CharField(max_length=120)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    name = models.CharField(max_length=120, verbose_name='Название')
    slug = models.SlugField(unique=True)
    description = RichTextField(verbose_name='Описание')
    photo = models.ImageField(upload_to='photos/', null=True, blank=True, verbose_name='Фото')
    file = models.FileField(upload_to='files/', null=True, blank=True, verbose_name='Файлы')
    started = models.DateTimeField(auto_now_add=True, verbose_name='Начало')
    ended = models.DateTimeField(blank=True, null=True, verbose_name='Закончился')
    deadline = models.DateField(verbose_name='Дедлайн до')
    tags = models.ManyToManyField(Tag, verbose_name='Теги')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.slug})


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=120, verbose_name='Название')
    description = RichTextField(verbose_name='Описание')
    status = models.CharField(choices=STATUS, max_length=120, verbose_name='Статус')
    deadline = models.DateField(verbose_name='Дедлайн до')
    started = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')
    priority = models.CharField(choices=PRIORITY, max_length=60, verbose_name='Приоритет')


    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')
    text = RichTextField(verbose_name='Текст')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.project} - {self.user}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class ProjectGroup(Group):
    group_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='group_author', verbose_name='Автор группы')
    assistants = models.ManyToManyField(User, verbose_name='Ассистенты', related_name='assistant')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')

mainapp/forms.py
from django import forms
from tempus_dominus.widgets import DatePicker
from django.contrib.auth.models import Group
from django_select2.forms import Select2MultipleWidget

from .models import Comment, Project, ProjectGroup, Task


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

        widgets = {
            'text': forms.Textarea()
        }


class CreteProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description', 'photo', 'file', 'deadline', 'tags')

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Имя проекта'}, ),
            'description': forms.Textarea(),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control'}),
            'deadline': DatePicker(),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'})
        }


class CreateNewGroupForm(forms.ModelForm):
    class Meta:
        model = ProjectGroup
        fields = ('name', 'assistants', 'project')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Выберите название группы'}),
            'assistants': Select2MultipleWidget(
                attrs={'style': 'width: 100%', 'data-placeholder': 'Выберите сотрудников'}),
            'project': forms.Select(attrs={'class': 'form-control'}),
        }

    def save(self):
        assistants = self.cleaned_data['assistants']
        user = super().save(commit=True)
        group_name = self.cleaned_data['name']
        author = ProjectGroup.objects.get(name=group_name)
        author.group_author.groups.add(
            Group.objects.get(name=group_name))  # Adding Project Author to the development group
        for assist in assistants:
            assist.groups.add(Group.objects.get(name=Group.objects.get(name=group_name)))

        return user


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'status', 'deadline', 'priority')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'deadline': DatePicker(),
            'priority': forms.Select(attrs={'class': 'form-control'}),
        }

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q

from .models import Project, Comment, ProjectGroup, Task
from .forms import AddCommentForm, CreteProjectForm, CreateNewGroupForm, CreateTaskForm
from .permissions import UserInGroupPermissionMixin, OnlyAuthorMixin, OnlyGroupAuthorMixin


# PROJECT RENDERING SECTION
class ProjectsListView(LoginRequiredMixin, ListView):
    template_name = 'mainapp/index/index.html'
    model = Project
    context_object_name = 'projects'
    login_url = 'authentication:login'


class UserProjectListView(ListView):
    template_name = 'mainapp/index/user_project.html'
    model = User
    context_object_name = 'projects'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('slug'))
        projects = user.project_set.all()
        return projects


class UserProjectDetailView(DetailView):
    model = Project
    template_name = 'mainapp/project_details/project_details.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_group = ProjectGroup.objects.filter(project__slug=self.kwargs.get('slug'))

        context['group_details'] = user_group
        context['comment_form'] = AddCommentForm
        return context


class SearchProjects(ListView):
    model = Project
    template_name = 'mainapp/search_projects/search_projects.html'
    context_object_name = 'projects'

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('search-projects')
        if query:
            queryset = Project.objects.filter(Q(name__iregex=query) | Q(tags__tag__iregex=query)).distinct()
        return queryset


# PROJECT MANIPULATIONS SECTION
class CreateProject(CreateView):
    model = Project
    form_class = CreteProjectForm
    template_name = 'mainapp/project_manipulations/create_project.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.slug})


class UpdateProject(OnlyAuthorMixin, UpdateView):
    model = Project
    form_class = CreteProjectForm
    template_name = 'mainapp/project_manipulations/update_project.html'

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.slug})


class DeleteProject(OnlyAuthorMixin, DeleteView):
    model = Project
    template_name = 'mainapp/index/user_project.html'

    def get_success_url(self):
        return reverse('mainapp:user_proj', kwargs={'slug': self.request.user})


# COMMENT SECTION
class AddComment(CreateView):
    model = Comment
    template_name = 'mainapp/project_details/project_details.html'
    form_class = AddCommentForm

    def form_valid(self, form):
        form.instance.project = Project.objects.get(slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


class DeleteComment(OnlyAuthorMixin, DeleteView):
    model = Comment
    template_name = 'mainapp/project_details/project_details.html'

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


# GROUP SECTION

class GroupListView(ListView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/groups.html'
    context_object_name = 'groups'

    def get_queryset(self):
        return ProjectGroup.objects.filter(project__slug=self.kwargs.get('slug'))


class CreateGroup(CreateView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/create_group.html'
    form_class = CreateNewGroupForm
    success_url = '/'

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['project'].queryset = self.request.user.project_set.all()
        return form

    def form_valid(self, form):
        form.instance.group_author = self.request.user
        instance = form.save()
        instance.permissions.set([33, 34, 35])  # id of permissions: add_task, change_task, delete_task
        instance.save()
        return super().form_valid(form)


class EditGroup(OnlyGroupAuthorMixin, UpdateView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/edit_group.html'
    form_class = CreateNewGroupForm

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['project'].queryset = self.request.user.project_set.all()
        return form

    def get_success_url(self):
        return reverse('mainapp:groups_list', kwargs={'slug': self.object.project.slug})


class DeleteGroup(OnlyGroupAuthorMixin, DeleteView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/groups.html'

    def get_success_url(self):
        return reverse('mainapp:groups_list', kwargs={'slug': self.object.project.slug})


# TASK SECTION
class CreateTask(UserInGroupPermissionMixin, CreateView):
    model = Task
    template_name = 'mainapp/task_manipulations/create_task.html'
    form_class = CreateTaskForm

    def form_valid(self, form):
        form.instance.project = Project.objects.get(slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


class EditTask(UserInGroupPermissionMixin, UpdateView):
    model = Task
    template_name = 'mainapp/task_manipulations/edit_task.html'
    form_class = CreateTaskForm

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


class DeleteTask(UserInGroupPermissionMixin, DeleteView):
    model = Task
    template_name = 'mainapp/project_details/project_details.html'

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})

templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src=   
    "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">   
        </script>   
        
        <script src=   
    "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">   
        </script>   
        
        <link href=   
    "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
            rel="stylesheet" type="text/css" />  
    <title>{% block title %}Главная{% endblock %}</title>
</head>
<body>
    {% block header %}
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'mainapp:main' %}">Navbar</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                      </li>
                       
                    </ul>
                    <form action="{% url 'mainapp:search_projects' %}" class="d-flex me-3" method="get">
                      <input id="tags" class="form-control me-2" name="search-projects" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <p class="mt-2"><a href="{% url 'mainapp:user_proj' user.username %}">{{ user.username }}</a> | <a class="btn btn-outline-dark" href="{% url 'authentication:logout' %}">Выйти</a></p>

                  </div>
                </div>
              </nav>
        </div>
    </header>
    {% endblock %}

    {% block content %}{% endblock %}

    <script> 
      $( function() { 
        var availableTags = [ 
            {% for project in projects %} 
                "{{project.name}}", 
            {% endfor %} 
            {% for tag in tags %} 
                "{{tag.tag}}", 
            {% endfor %} 
        ]; 
        $( "#tags" ).autocomplete({ 
          source: availableTags 
        }); 
      } ); 
      </script> 
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>