main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, include
from .views import (ProjectsListView, UserProjectListView, UserProjectDetailView, AddComment, DeleteComment,
                    CreateProject, UpdateProject, DeleteProject, CreateGroup, CreateTask, EditTask, DeleteTask,
                    EditGroup, DeleteGroup, GroupListView, SearchProjects)

app_name = 'mainapp'

urlpatterns = [
    path("select2/", include("django_select2.urls")),

    # PROJECT SECTION
    path('', ProjectsListView.as_view(), name='main'),
    path('<slug:slug>', UserProjectListView.as_view(), name='user_proj'),
    path('create-project/', CreateProject.as_view(), name='new_project'),
    path('update-project/<slug:slug>/', UpdateProject.as_view(), name='update_project'),
    path('delete-project/<slug:slug>/', DeleteProject.as_view(), name='delete_project'),
    path('project/<slug:slug>/', UserProjectDetailView.as_view(), name='proj_details'),
    path('search/', SearchProjects.as_view(), name='search_projects'),

    # COMMENT SECTION
    path('project/<slug:slug>/add-comment/', AddComment.as_view(), name='add_comment'),
    path('delete-comment/<int:pk>/', DeleteComment.as_view(), name='delete_comment'),

    # GROUP SECTION
    path('<slug:slug>/project-groups/', GroupListView.as_view(), name='groups_list'),
    path('create-group/', CreateGroup.as_view(), name='create_group'),
    path('edit-group/<int:pk>/', EditGroup.as_view(), name='edit_group'),
    path('delete-group/<int:pk>/', DeleteGroup.as_view(), name='delete_group'),

    # TASK SECTION
    path('project/<slug:slug>/create-task/', CreateTask.as_view(), name='create_task'),
    path('project/<slug:slug>/edit-task/<int:pk>/', EditTask.as_view(), name='edit_task'),
    path('project/<slug:slug>/delete-task/<int:pk>/', DeleteTask.as_view(), name='delete_task'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from unidecode import unidecode
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.contrib.auth.models import Group

STATUS = (
    ('Стартовал', 'Started'),
    ('В процессе', 'In process'),
    ('Завершен', 'Finished'),
)

PRIORITY = (
    ('Низкий', 'Low'),
    ('Средний', 'Medium'),
    ('Высокий', 'High'),
    ('Наивысший', 'Highest'),
)


class Tag(models.Model):
    tag = models.CharField(max_length=120)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    name = models.CharField(max_length=120, verbose_name='Название')
    slug = models.SlugField(unique=True)
    description = RichTextField(verbose_name='Описание')
    photo = models.ImageField(upload_to='photos/', null=True, blank=True, verbose_name='Фото')
    file = models.FileField(upload_to='files/', null=True, blank=True, verbose_name='Файлы')
    started = models.DateTimeField(auto_now_add=True, verbose_name='Начало')
    ended = models.DateTimeField(blank=True, null=True, verbose_name='Закончился')
    deadline = models.DateField(verbose_name='Дедлайн до')
    tags = models.ManyToManyField(Tag, verbose_name='Теги')

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.slug})


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=120, verbose_name='Название')
    description = RichTextField(verbose_name='Описание')
    status = models.CharField(choices=STATUS, max_length=120, verbose_name='Статус')
    deadline = models.DateField(verbose_name='Дедлайн до')
    started = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')
    priority = models.CharField(choices=PRIORITY, max_length=60, verbose_name='Приоритет')


    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Task, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')
    text = RichTextField(verbose_name='Текст')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.project} - {self.user}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class ProjectGroup(Group):
    group_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='group_author', verbose_name='Автор группы')
    assistants = models.ManyToManyField(User, verbose_name='Ассистенты', related_name='assistant')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='Проект')

mainapp/forms.py
from django import forms
from tempus_dominus.widgets import DatePicker
from django.contrib.auth.models import Group
from django_select2.forms import Select2MultipleWidget

from .models import Comment, Project, ProjectGroup, Task


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

        widgets = {
            'text': forms.Textarea()
        }


class CreteProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('name', 'description', 'photo', 'file', 'deadline', 'tags')

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Имя проекта'}, ),
            'description': forms.Textarea(),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control'}),
            'deadline': DatePicker(),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'})
        }


class CreateNewGroupForm(forms.ModelForm):
    class Meta:
        model = ProjectGroup
        fields = ('name', 'assistants', 'project')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Выберите название группы'}),
            'assistants': Select2MultipleWidget(
                attrs={'style': 'width: 100%', 'data-placeholder': 'Выберите сотрудников'}),
            'project': forms.Select(attrs={'class': 'form-control'}),
        }

    def save(self):
        assistants = self.cleaned_data['assistants']
        user = super().save(commit=True)
        group_name = self.cleaned_data['name']
        author = ProjectGroup.objects.get(name=group_name)
        author.group_author.groups.add(
            Group.objects.get(name=group_name))  # Adding Project Author to the development group
        for assist in assistants:
            assist.groups.add(Group.objects.get(name=Group.objects.get(name=group_name)))

        return user


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'status', 'deadline', 'priority')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'deadline': DatePicker(),
            'priority': forms.Select(attrs={'class': 'form-control'}),
        }

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q

from .models import Project, Comment, ProjectGroup, Task
from .forms import AddCommentForm, CreteProjectForm, CreateNewGroupForm, CreateTaskForm
from .permissions import UserInGroupPermissionMixin, OnlyAuthorMixin, OnlyGroupAuthorMixin


# PROJECT RENDERING SECTION
class ProjectsListView(LoginRequiredMixin, ListView):
    template_name = 'mainapp/index/index.html'
    model = Project
    context_object_name = 'projects'
    login_url = 'authentication:login'


class UserProjectListView(ListView):
    template_name = 'mainapp/index/user_project.html'
    model = User
    context_object_name = 'projects'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('slug'))
        projects = user.project_set.all()
        return projects


class UserProjectDetailView(DetailView):
    model = Project
    template_name = 'mainapp/project_details/project_details.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_group = ProjectGroup.objects.filter(project__slug=self.kwargs.get('slug'))

        context['group_details'] = user_group
        context['comment_form'] = AddCommentForm
        return context


class SearchProjects(ListView):
    model = Project
    template_name = 'mainapp/search_projects/search_projects.html'
    context_object_name = 'projects'

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('search-projects')
        if query:
            queryset = Project.objects.filter(Q(name__iregex=query) | Q(tags__tag__iregex=query)).distinct()
        return queryset


# PROJECT MANIPULATIONS SECTION
class CreateProject(CreateView):
    model = Project
    form_class = CreteProjectForm
    template_name = 'mainapp/project_manipulations/create_project.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.slug})


class UpdateProject(OnlyAuthorMixin, UpdateView):
    model = Project
    form_class = CreteProjectForm
    template_name = 'mainapp/project_manipulations/update_project.html'

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.slug})


class DeleteProject(OnlyAuthorMixin, DeleteView):
    model = Project
    template_name = 'mainapp/index/user_project.html'

    def get_success_url(self):
        return reverse('mainapp:user_proj', kwargs={'slug': self.request.user})


# COMMENT SECTION
class AddComment(CreateView):
    model = Comment
    template_name = 'mainapp/project_details/project_details.html'
    form_class = AddCommentForm

    def form_valid(self, form):
        form.instance.project = Project.objects.get(slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


class DeleteComment(OnlyAuthorMixin, DeleteView):
    model = Comment
    template_name = 'mainapp/project_details/project_details.html'

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


# GROUP SECTION

class GroupListView(ListView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/groups.html'
    context_object_name = 'groups'

    def get_queryset(self):
        return ProjectGroup.objects.filter(project__slug=self.kwargs.get('slug'))


class CreateGroup(CreateView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/create_group.html'
    form_class = CreateNewGroupForm
    success_url = '/'

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['project'].queryset = self.request.user.project_set.all()
        return form

    def form_valid(self, form):
        form.instance.group_author = self.request.user
        instance = form.save()
        instance.permissions.set([33, 34, 35])  # id of permissions: add_task, change_task, delete_task
        instance.save()
        return super().form_valid(form)


class EditGroup(OnlyGroupAuthorMixin, UpdateView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/edit_group.html'
    form_class = CreateNewGroupForm

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields['project'].queryset = self.request.user.project_set.all()
        return form

    def get_success_url(self):
        return reverse('mainapp:groups_list', kwargs={'slug': self.object.project.slug})


class DeleteGroup(OnlyGroupAuthorMixin, DeleteView):
    model = ProjectGroup
    template_name = 'mainapp/group_manipulations/groups.html'

    def get_success_url(self):
        return reverse('mainapp:groups_list', kwargs={'slug': self.object.project.slug})


# TASK SECTION
class CreateTask(UserInGroupPermissionMixin, CreateView):
    model = Task
    template_name = 'mainapp/task_manipulations/create_task.html'
    form_class = CreateTaskForm

    def form_valid(self, form):
        form.instance.project = Project.objects.get(slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


class EditTask(UserInGroupPermissionMixin, UpdateView):
    model = Task
    template_name = 'mainapp/task_manipulations/edit_task.html'
    form_class = CreateTaskForm

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})


class DeleteTask(UserInGroupPermissionMixin, DeleteView):
    model = Task
    template_name = 'mainapp/project_details/project_details.html'

    def get_success_url(self):
        return reverse('mainapp:proj_details', kwargs={'slug': self.object.project.slug})

templates/mainapp/project_details/project_details.html
{% extends 'mainapp/base.html' %}

{% block title %}{{ project.name }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col mb-5">
            <h1>{{ project.name }}</h1>
            <p>{{ project.description|safe }}</p>
        </div>

        <h4>Текущие задачи</h4>

        {% if project.task_set.all %}
            {% if project.user == user %}
                <a href="{% url 'mainapp:create_task' project.slug %}">Создать Новую</a>
            {% elif group_details|length == 0 %}
            {% elif perms.mainapp.add_task %}
                <a href="{% url 'mainapp:create_task' project.slug %}">Создать Новую</a>
            {% endif %}
            {% for tasks in project.task_set.all %}
                <div class="col-md-6 mt-3"> 
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ tasks.title }}</h5>
                            <strong>Описание</strong>: {{ tasks.description|safe }}
                            <p class="card-text"><strong>Начал</strong>: {{ tasks.user }}</p>
                            <p class="card-text"><strong>Начало</strong>: {{ tasks.started }}</p>
                            <p class="card-text"><strong>Дедлайн</strong>: {{ tasks.deadline }}</p>
                            <p class="card-text"><strong>Приоритет</strong>: 
                                {% if tasks.priority == 'Низкий' %} <i class="fa-solid fa-square fa-sm" style="color: #11d031;"></i>
                                    {{ tasks.priority }}
                                {% elif tasks.priority == 'Средний' %} <i class="fa-solid fa-square fa-sm" style="color: #cc9d19;"></i>
                                    {{ tasks.priority }}
                                {% elif tasks.priority == 'Высокий' %} <i class="fa-solid fa-square fa-sm" style="color: #e240dd;"></i>
                                    {{ tasks.priority }}
                                {% elif tasks.priority == 'Наивысший' %} <i class="fa-solid fa-square fa-sm" style="color: #d02525;"></i>
                                    {{ tasks.priority }}
                                {% endif %}
                            </p>

                            {% if project.user == user %}
                                <form class="float-end ms-2" action="{% url 'mainapp:delete_task' project.slug tasks.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-success">Удалить</button>
                                </form>
                                <a class="btn btn-outline-success float-end" href="{% url 'mainapp:edit_task' project.slug tasks.id %}">Редактировать</a>
                            {% elif group_details|length == 0 %}
                            {% elif perms.mainapp.change_task %}
                                <form class="float-end ms-2" action="{% url 'mainapp:delete_task' project.slug tasks.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-success">Удалить</button>
                                </form>
                                
                                <a class="btn btn-outline-success float-end" href="{% url 'mainapp:edit_task' project.slug tasks.id %}">Редактировать</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}

        {% else %}
            {% if project.user == user %}
                <h5>На данный момент задач не <a href="{% url 'mainapp:create_task' project.slug %}">найдено!</a></h5>
            {% elif group_details|length == 0 %}
                <h5>На данный момент задач не найдено!</h5>
            {% elif perms.mainapp.add_task %}
                <h5>На данный момент задач не <a href="{% url 'mainapp:create_task' project.slug %}">найдено!</a></h5>
            {% endif %}
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-7">
            <h2 class="mt-5">Add Comment</h2>
            <form class="mb-5 mt-4" action="{% url 'mainapp:add_comment' project.slug %}" method="post">
                {% csrf_token %}
                {{comment_form.media}}
                {{comment_form.text }}
                <button class="btn btn-outline-dark float-end mt-3" type="submit">отправить</button>
            </form><br>
            <hr>
            <h2 class="mb-4">Comments</h2>
            {% for comments in project.comment_set.all %}
                {% if comments.user == user %}
                <form action="{% url 'mainapp:delete_comment' comments.pk %}" method="post">
                    {% csrf_token %}
                    <i class="fa-solid fa-user fa-sm"></i>  {{ comments.user }} &nbsp;&nbsp;&nbsp;&nbsp; <i class="fa-regular fa-calendar-days fa-sm"></i> {{ comments.dateCreation }}
                    <button class="btn btn-link text-dark text-decoration-none">[ Удалить ]</button>
                </form>
                {% else %}
                <i class="fa-solid fa-user fa-sm"></i>  {{ comments.user }} &nbsp;&nbsp;&nbsp;&nbsp; <i class="fa-regular fa-calendar-days fa-sm"></i> {{ comments.dateCreation }}
                {% endif %}
                {{ comments.text|safe }}<br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}