authentication/urls.py
from django.urls import path
from .views import UserLogin, UserSignup, UserLogout

app_name = 'authentication'

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('registration/', UserSignup.as_view(), name='registration'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('authentication/', include('authentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import Group


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'autofocus': True}), label='Логин')
    password = forms.CharField(
        label=('Пароль'),
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )


class UserSignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(), label='Логин')
    email = forms.CharField(widget=forms.EmailInput(), label='Email')
    password1 = forms.CharField(
        label=('Пароль'),
        widget=forms.PasswordInput(),
    )
    password2 = forms.CharField(
        label=('Еще раз'),
        widget=forms.PasswordInput(),
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self):
        user = super(UserSignupForm, self).save(self.request)
        group = Group.objects.get(name='NEW_USERS')
        group.user_set.add(user)
        return user

authentication/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from .forms import UserLoginForm, UserSignupForm


class UserLogin(LoginView):
    template_name = 'authentication/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('mainapp:main')


class UserSignup(CreateView):
    form_class = UserSignupForm
    template_name = 'authentication/registration.html'
    success_url = reverse_lazy('authentication:login')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        return form


class UserLogout(LogoutView):
    template_name = 'mainapp/base.html'

    def get_success_url(self):
        return reverse_lazy('authentication:login')

templates/authentication/login.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <title>Логин</title>
</head>
<body>
    <section class="vh-100" style="background: linear-gradient(to right, blue, pink);">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card shadow-2-strong" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
      
                  <form action="" method="post">
                    {% csrf_token %}
                    <h3 class="mb-5">Логин</h3>
                    {% for f in form %}
                    <div class="form-outline mb-4">
                        <input name="{{ f.name }}" type="{{ f.field.widget.input_type }}" id="{{ f.id_for_label }}" class="form-control form-control-lg" />
                        <label class="form-label" for="{{ f.label_for_id }}">{{ f.label }}</label>
                    </div>
                  {% endfor %}
                  <div class="text-danger">{{form.non_field_errors}}</div>
                    
                    <div class="d-grid gap-2">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Логин</button>
                    <p>Все еще не зарегестрировались? <a href="{% url 'authentication:registration' %}">Регистрация</a></p>
                    <hr class="my-4">
                    </div>
                  </form>
                  <form method="post" action="{% provider_login_url 'yandex' process='login' %}">
                    {% csrf_token %}
                    <div class="d-grid gap-2">
                      <button type="submit" class="btn btn-lg btn-block btn-primary" style="background-color: #dd4b39;"
                      type="submit"><i class="fab fa-yandex me-2"></i>Войти с помощью Яндекс</button>
                    </div>
                 </form>
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/authentication/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <title>Регистрация</title>
</head>
<body>
    <section class="vh-100" style="background: radial-gradient(red, blue);">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card shadow-2-strong" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
      
                  <form action="" method="post">
                    {% csrf_token %}
                    <h3 class="mb-5">Регистрация</h3>
                    {% for f in form %}
                    <div class="form-outline mb-4">
                        <input name="{{ f.name }}" type="{{ f.field.widget.input_type }}" id="typeEmailX-2" class="form-control form-control-lg" />
                        <label class="form-label" for="{{ f.label_for_id }}">{{ f.label }}</label>
                    </div>
                    {% endfor %}
                    <div class="text-danger">{{form.non_field_errors}}</div>
                    <div class="d-grid gap-2">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Регистрация</button>
                    <p>Уже есть аккаунт? <a href="{% url 'authentication:login' %}">Логин</a></p>
                    </div>
                  </form>
      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>